apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todo
  name: todo
spec:
  path:
    /was855-todo-app
  port:
    targetPort: http
  to:
    kind: Service
    name: todo
    weight: 100
