apiVersion: v1
kind: Service
metadata:
  labels:
    app: was855todoappearear
  name: was855todoappearear
spec:
  type: NodePort
  ports:
    - name: http
      port: 9080
      targetPort: 9080
  selector:
    app: was855todoappearear
