apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: using-build-and-deploy-
spec:
  pipelineRef:
    name: build-and-deploy
  workspaces:
  - name: build-workspace
    persistentVolumeClaim:
      claimName: shared-task-storage
  params:
  - name: repo-url
    value: https://github.com/keunlee/was855-todo-app-on-ocp.git
  - name: branch-name
    value: main
  - name: repo-dockerfile
    value: Dockerfile
  - name: image-url
    value: image-registry.openshift-image-registry.svc:5000/demo-todo-was855/was855todoappearear:latest
  - name: repo-context
    value: was855-todo-app-migration
